import { Stock, PrivateCompany } from './types';

export const STOCK_DATA: Stock[] = [
  // --- AI & Compute Giants ---
  {
    ticker: "NVDA",
    name: "NVIDIA Corp",
    price: 178.88,
    change: -0.97,
    category: "AI & Compute",
    role: "AI Training Silicon",
    description: "The hegemon of AI training. Supplier of H100/Blackwell GPUs used in Apple's Private Cloud Compute training clusters.",
    marketCap: "4.35T",
    risk: "Low",
    growthPotential: "+35%",
    region: "US",
    tags: ["Chips", "Data Center"]
  },
  {
    ticker: "TSM",
    name: "TSMC",
    price: 275.06,
    change: -0.88,
    category: "Manufacturing",
    role: "Advanced Foundry (3nm)",
    description: "Sole manufacturer of Apple Silicon (M-Series/A-Series). The bottleneck for all advanced AI logic.",
    marketCap: "1.2T",
    risk: "Low",
    growthPotential: "+28%",
    region: "Asia",
    tags: ["Apple Direct", "Chips", "Geopolitical Risk"]
  },
  {
    ticker: "AMD",
    name: "Advanced Micro Devices",
    price: 203.78,
    change: 1.24,
    category: "AI & Compute",
    role: "Merchant Silicon / ROCm",
    description: "Primary NVIDIA rival. Apple uses AMD graphics IP in older Macs and potentially future external compute solutions.",
    marketCap: "380B",
    risk: "Medium",
    growthPotential: "+22%",
    region: "US",
    tags: ["Chips"]
  },
  {
    ticker: "AVGO",
    name: "Broadcom Inc.",
    price: 341.45,
    change: 0.37,
    category: "AI & Compute",
    role: "Custom ASIC & Networking",
    description: "Key partner for custom silicon (like Google TPU) and likely involved in Apple's internal modem/Wi-Fi chip designs.",
    marketCap: "1.6T",
    risk: "Low",
    growthPotential: "+18%",
    region: "US",
    tags: ["Apple Direct", "Chips", "Connectivity"]
  },
  {
    ticker: "ARM",
    name: "Arm Holdings",
    price: 185.50,
    change: 2.10,
    category: "AI & Compute",
    role: "Instruction Set Architecture",
    description: "The architectural foundation of Apple Silicon. Apple holds a perpetual license to the ARM ISA.",
    marketCap: "190B",
    risk: "Medium",
    growthPotential: "+20%",
    region: "Europe",
    tags: ["Apple Direct", "IP Licensing"]
  },
  {
    ticker: "INTC",
    name: "Intel Corp",
    price: 34.50,
    change: 3.14,
    category: "AI & Compute",
    role: "Foundry & Legacy CPU",
    description: "Potential future foundry partner for Apple. Currently struggling to pivot to IDM 2.0 model.",
    marketCap: "145B",
    risk: "High",
    growthPotential: "+12%",
    region: "US",
    tags: ["US Reshoring", "Chips", "Turnaround"]
  },
  
  // --- Strategic Materials (Apple Specific) ---
  {
    ticker: "GLW",
    name: "Corning Inc.",
    price: 79.47,
    change: 1.85,
    category: "Strategic Materials",
    role: "Ceramic Shield",
    description: "Co-developed proprietary nanocrystal glass with Apple. Exclusive supplier for iPhone Pro display protection.",
    marketCap: "68.1B",
    risk: "Low",
    growthPotential: "+8%",
    region: "US",
    tags: ["Apple Direct", "Materials"]
  },
  {
    ticker: "MP",
    name: "MP Materials",
    price: 55.26,
    change: -2.51,
    category: "Strategic Materials",
    role: "Recycled Magnets",
    description: "Operates Mountain Pass mine. Exclusive partner for closed-loop recycled neodymium magnets in iPhone Taptic Engines.",
    marketCap: "9.8B",
    risk: "Medium",
    growthPotential: "+40%",
    region: "US",
    tags: ["Apple Direct", "US Reshoring", "Materials", "Green Tech"]
  },
  {
    ticker: "ATI",
    name: "ATI Inc.",
    price: 96.47,
    change: 1.76,
    category: "Metals & Mining",
    role: "Titanium (Aerospace)",
    description: "Key supplier of Grade 5 Titanium alloy used in iPhone Pro chassis. Beneficiary of US-sourcing initiatives.",
    marketCap: "12.9B",
    risk: "Medium",
    growthPotential: "+15%",
    region: "US",
    tags: ["Materials", "US Reshoring"]
  },
  {
    ticker: "AA",
    name: "Alcoa Corp",
    price: 42.50,
    change: 0.30,
    category: "Metals & Mining",
    role: "Elysys Aluminum (Parent)",
    description: "Parent company of the Elysys JV (with Rio Tinto) producing carbon-free 'Green Aluminum' for Apple.",
    marketCap: "7.6B",
    risk: "Medium",
    growthPotential: "+5%",
    region: "US",
    tags: ["Apple Direct", "Materials", "Green Tech"]
  },
  {
    ticker: "RIO",
    name: "Rio Tinto",
    price: 74.20,
    change: -0.45,
    category: "Metals & Mining",
    role: "Elysys Aluminum (Parent)",
    description: "Mining giant and co-owner of the Elysys zero-carbon smelting technology used in Apple products.",
    marketCap: "120B",
    risk: "Low",
    growthPotential: "+6%",
    region: "Europe",
    tags: ["Apple Direct", "Materials", "Green Tech"]
  },
  {
    ticker: "LQMT",
    name: "Liquidmetal Tech",
    price: 0.131,
    change: -2.24,
    category: "Strategic Materials",
    role: "Amorphous Metal IP",
    description: "Penny stock holding IP rights for bulk metallic glass. Apple owns a perpetual exclusive license.",
    marketCap: "120M",
    risk: "Extreme",
    growthPotential: "+150%",
    region: "US",
    tags: ["Apple Direct", "Materials", "Penny Stock", "IP Licensing"]
  },

  // --- Quantum Hardware ---
  {
    ticker: "IONQ",
    name: "IonQ Inc.",
    price: 41.71,
    change: 1.73,
    category: "Quantum",
    role: "Trapped Ion Computing",
    description: "Leader in Trapped Ion quantum computers. High fidelity qubits suitable for hybrid AI/Quantum workflows.",
    marketCap: "8.5B",
    risk: "High",
    growthPotential: "+65%",
    region: "US",
    tags: ["Quantum", "US Reshoring"]
  },
  {
    ticker: "RGTI",
    name: "Rigetti Computing",
    price: 23.59,
    change: 3.46,
    category: "Quantum",
    role: "Superconducting Qubits",
    description: "Full-stack quantum computing company operating Fab-1. Developing multi-chip quantum processors.",
    marketCap: "3.2B",
    risk: "High",
    growthPotential: "+55%",
    region: "US",
    tags: ["Quantum", "US Reshoring"]
  },
  {
    ticker: "QBTS",
    name: "D-Wave Quantum",
    price: 20.44,
    change: -0.49,
    category: "Quantum",
    role: "Quantum Annealing",
    description: "Focuses on optimization problems using quantum annealing. Often used for logistics and scheduling.",
    marketCap: "2.8B",
    risk: "High",
    growthPotential: "+45%",
    region: "North America",
    tags: ["Quantum"]
  },
  {
    ticker: "IBM",
    name: "IBM",
    price: 297.44,
    change: 2.42,
    category: "Quantum",
    role: "Superconducting & Qiskit",
    description: "The 'Big Blue' of quantum. Creator of Qiskit and the Heron/Eagle processors. Massive cloud fleet.",
    marketCap: "275B",
    risk: "Low",
    growthPotential: "+10%",
    region: "US",
    tags: ["Quantum", "AI"]
  },

  // --- Semiconductor Equipment & Materials ---
  {
    ticker: "ASML",
    name: "ASML Holding",
    price: 981.04,
    change: -1.47,
    category: "Semi Equip",
    role: "EUV Lithography",
    description: "Monopoly on Extreme Ultraviolet Lithography machines required to print Apple's 3nm/2nm chips.",
    marketCap: "375B",
    risk: "Medium",
    growthPotential: "+18%",
    region: "Europe",
    tags: ["Chips", "Monopoly"]
  },
  {
    ticker: "AMAT",
    name: "Applied Materials",
    price: 260.15,
    change: -1.15,
    category: "Semi Equip",
    role: "Wafer Fabrication Equip",
    description: "Provides the machinery for modifying materials at atomic levels. Critical for display and chip manufacturing.",
    marketCap: "215B",
    risk: "Medium",
    growthPotential: "+16%",
    region: "US",
    tags: ["Chips", "US Reshoring"]
  },
  {
    ticker: "LRCX",
    name: "Lam Research",
    price: 139.59,
    change: -0.96,
    category: "Semi Equip",
    role: "Etch & Deposition",
    description: "Specializes in wafer fabrication equipment, specifically etching silicon for 3D NAND and logic.",
    marketCap: "175B",
    risk: "Medium",
    growthPotential: "+17%",
    region: "US",
    tags: ["Chips", "US Reshoring"]
  },
  {
    ticker: "SNPS",
    name: "Synopsys",
    price: 385.60,
    change: -0.18,
    category: "Semi Equip",
    role: "EDA Software",
    description: "Provides the software tools (EDA) Apple uses to design the A-Series and M-Series chips.",
    marketCap: "72B",
    risk: "Low",
    growthPotential: "+14%",
    region: "US",
    tags: ["Apple Direct", "Software"]
  },
  {
    ticker: "WOLF",
    name: "Wolfspeed",
    price: 25.40,
    change: 1.20,
    category: "Semi Equip",
    role: "Silicon Carbide (SiC)",
    description: "Leader in SiC wafers used for high-efficiency power management in data centers and EVs.",
    marketCap: "3.2B",
    risk: "High",
    growthPotential: "+30%",
    region: "US",
    tags: ["Materials", "US Reshoring"]
  },

  // --- Battery & Mining ---
  {
    ticker: "ALB",
    name: "Albemarle Corp",
    price: 116.82,
    change: 0.34,
    category: "Battery & Power",
    role: "Lithium Mining",
    description: "World's largest lithium provider. Critical feeder for the battery supply chain used in all mobile devices.",
    marketCap: "13.7B",
    risk: "Medium",
    growthPotential: "+25%",
    region: "US",
    tags: ["Materials", "Battery"]
  },
  {
    ticker: "GLNCY",
    name: "Glencore",
    price: 12.45,
    change: -0.50,
    category: "Battery & Power",
    role: "Cobalt Mining",
    description: "Major cobalt supplier. Apple partners with them for ethical auditing of cobalt mines in the DRC.",
    marketCap: "65B",
    risk: "Medium",
    growthPotential: "+12%",
    region: "Europe",
    tags: ["Apple Direct", "Materials", "Battery"]
  },
  {
    ticker: "UMICY",
    name: "Umicore",
    price: 24.80,
    change: 0.15,
    category: "Battery & Power",
    role: "Cathode Recycling",
    description: "Global materials technology group. Key partner in closing the loop on battery recycling and refining.",
    marketCap: "6B",
    risk: "Medium",
    growthPotential: "+15%",
    region: "Europe",
    tags: ["Apple Direct", "Recycling", "Green Tech"]
  },

  // --- Components & Connectivity ---
  {
    ticker: "SWKS",
    name: "Skyworks Solutions",
    price: 60.50,
    change: -3.34,
    category: "Components",
    role: "RF Filters",
    description: "Heavily dependent on Apple. Makes the radio frequency chips that allow iPhones to connect to 5G/6G.",
    marketCap: "9B",
    risk: "Medium",
    growthPotential: "+9%",
    region: "US",
    tags: ["Apple Direct", "Connectivity"]
  },
  {
    ticker: "QRVO",
    name: "Qorvo Inc",
    price: 85.20,
    change: -1.10,
    category: "Components",
    role: "RF Modules",
    description: "Competitor/Peer to Skyworks. Supplies critical RF amplifiers and filters for mobile connectivity.",
    marketCap: "8.2B",
    risk: "Medium",
    growthPotential: "+10%",
    region: "US",
    tags: ["Apple Direct", "Connectivity"]
  },
  {
    ticker: "STM",
    name: "STMicroelectronics",
    price: 21.97,
    change: -2.10,
    category: "Components",
    role: "Sensors & eSIM",
    description: "Supplies accelerometers, gyroscopes, and eSIM chips for iPhone and Apple Watch.",
    marketCap: "20B",
    risk: "Medium",
    growthPotential: "+11%",
    region: "Europe",
    tags: ["Apple Direct", "Chips"]
  },
  {
    ticker: "OLED",
    name: "Universal Display",
    price: 113.73,
    change: 1.27,
    category: "Components",
    role: "OLED IP",
    description: "Licenses the organic material IP used in every iPhone and Apple Watch OLED screen.",
    marketCap: "5.4B",
    risk: "High",
    growthPotential: "+15%",
    region: "US",
    tags: ["Apple Direct", "Display"]
  },
  {
    ticker: "MRAAY",
    name: "Murata Mfg",
    price: 35.60,
    change: 0.40,
    category: "Components",
    role: "MLCC Capacitors",
    description: "World leader in ceramic capacitors. An iPhone contains thousands of their tiny components.",
    marketCap: "22B",
    risk: "Low",
    growthPotential: "+7%",
    region: "Asia",
    tags: ["Apple Direct", "Components"]
  },

  // --- Manufacturing & Assembly ---
  {
    ticker: "HNHPF",
    name: "Hon Hai (Foxconn)",
    price: 15.47,
    change: -1.05,
    category: "Manufacturing",
    role: "Final Assembly",
    description: "The primary iPhone assembler. Innovator of the solid-state diffusion process for titanium bonding.",
    marketCap: "110B",
    risk: "Low",
    growthPotential: "+8%",
    region: "Asia",
    tags: ["Apple Direct", "Assembly", "Geopolitical Risk"]
  },
  {
    ticker: "JBL",
    name: "Jabil Inc.",
    price: 201.87,
    change: 0.85,
    category: "Manufacturing",
    role: "Precision Casings",
    description: "US-based manufacturer handling complex CNC machining for Apple's titanium and aluminum housings.",
    marketCap: "21.6B",
    risk: "Medium",
    growthPotential: "+9%",
    region: "US",
    tags: ["Apple Direct", "Assembly"]
  },
  {
    ticker: "BRK.B",
    name: "Berkshire Hathaway",
    price: 504.14,
    change: 0.44,
    category: "Metals & Mining",
    role: "Titanium Forging",
    description: "Owner of Precision Castparts (PCC) and TIMET, supplying melted and milled titanium products.",
    marketCap: "1.1T",
    risk: "Low",
    growthPotential: "+5%",
    region: "US",
    tags: ["Materials", "Conglomerate"]
  },
  {
    ticker: "TRYIY",
    name: "Toray Industries",
    price: 15.20,
    change: 0.10,
    category: "Manufacturing",
    role: "Carbon Fiber/Textiles",
    description: "Japanese giant in fibers. Likely supplier of base materials for TechWoven and high-performance fabrics.",
    marketCap: "12B",
    risk: "Medium",
    growthPotential: "+6%",
    region: "Asia",
    tags: ["Materials", "Textiles"]
  }
];

export const PRIVATE_DATA: PrivateCompany[] = [
  {
    name: "Elysys",
    status: "Joint Venture",
    owners: "Alcoa, Rio Tinto, Apple",
    role: "Carbon-Free Aluminum",
    description: "Proprietary smelting technology that releases oxygen instead of CO2. Exclusive to Apple for consumer electronics."
  },
  {
    name: "Bluefors",
    status: "Private",
    owners: "Private Equity",
    role: "Dilution Refrigerators",
    description: "The 'picks and shovels' of quantum. Manufactures the cryostats used by IBM, Google, and Rigetti."
  },
  {
    name: "Quantinuum",
    status: "Private/Spin-off",
    owners: "Honeywell, Cambridge Quantum",
    role: "Trapped Ion Quantum",
    description: "Merged entity of Honeywell Quantum Solutions and Cambridge Quantum. Leader in quantum volume."
  },
  {
    name: "PsiQuantum",
    status: "Private",
    owners: "VC Backed",
    role: "Photonic Quantum",
    description: "Building fault-tolerant quantum computers using silicon photonics. Partnered with GlobalFoundries."
  },
  {
    name: "GlobalFoundries",
    status: "Public (GFS)",
    owners: "Public",
    role: "Photonic Manufacturing",
    description: "Manufacturing partner for PsiQuantum's photonic chips. Included here for context on PsiQuantum relationship."
  },
  {
    name: "Luxshare Precision",
    status: "Shenzhen Listed",
    owners: "Public (China)",
    role: "Assembly / Vision Pro",
    description: "Primary assembler for Apple Vision Pro and growing share of iPhone assembly. Key Foxconn rival."
  }
];